// Generated by Elfenben v1.0.16
const chokidar = require('chokidar');
const contains = function(val,search) {
    return (val.indexOf(search) > 0);
};
const runElfenben = function(path) {
    return (require('child_process')).exec(`elfenben ${path}`,{
        cwd: process.cwd
    });
};
const fileHandler = function(path) {
    return (contains(path,'.elf') ?
        (function() {
            return runElfenben(path);
        })() :
        undefined);
};
const createAndStartWatcher = function() {
    const watcher = chokidar.watch('.',{
        ignored: '*.js',
        persistent: true,
        ignorePermissionErrors: false
    });
    watcher.on('change',function(path) {
        return fileHandler(path);
    });
    return null;
};
exports.createAndStartWatcher = createAndStartWatcher;
